version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}

      - run:
          name: Run Domain Module Unit Tests
          command: ./gradlew :domain:test
      - store_artifacts:
          path: domain/build/reports
      - store_test_results:
          path: domain/build/test-results

      - run:
          name: Run Gateway Module Unit Tests
          command: ./gradlew :gateway:testDebugUnitTest
      - store_artifacts:
          path: gateway/build/reports
      - store_test_results:
          path: gateway/build/test-results

      - run:
          name: Run Use Cases Module Unit Tests
          command: ./gradlew :usecases:testDebugUnitTest
      - store_artifacts:
          path: usecases/build/reports
      - store_test_results:
          path: usecases/build/test-results

      - run:
          name: Run Presentation Module Unit Tests
          command: ./gradlew :presentation:testDebugUnitTest
      - store_artifacts:
          path: presentation/build/reports
      - store_test_results:
          path: presentation/build/test-results

      - run:
          name: Run Lint Test
          command: ./gradlew lint
      - store_artifacts:
          path: lint/build/reports